### ISSUE TITLE
Implement area selection in Organization creation

### ISSUE THREAD

**Issue by maurizi** [azavea/temperate#1261]
# Overview

This is the first pass at the changes to the plan wizard to support area instead of point based indicators. Users will need to enter the cities/counties of interest when creating their organization, in the new "Geographic area" step.

_Note:_ The map view will be added in a later issue

# Demo

https://app.abstract.com/projects/a6f09a70-6bb8-11e7-b6ac-dd414f3e9f7c/branches/master/collections/da0bed50-0b0e-40fb-b9f5-ef25f7e58327?collectionLayerId=1ff1a34c-1f31-43af-9ed6-66487737a4de

# Tasks

 - [ ] Add the Geographic area step to the Plan wizard
 - [ ] The location chosen in the organization creation wizard should be shown as the starting area
 - [ ] Users can remove areas by "x" button
 - [ ] Users can add new areas using an autocomplete
 - [ ] Show the sq. mi. for each selected area, as well as the total sq. mi.

Blocked by #1260
