### ISSUE TITLE
Implement action card's evaluated action state

### ISSUE THREAD

**Issue by fungjj92** [azavea/temperate#311]
This is for when the action has been created for the risk, show the card in it's completed state.

### Screenshots

<img width="738" alt="screen shot 2018-01-09 at 5 02 21 pm" src="https://user-images.githubusercontent.com/10568752/34745571-f25d24d0-f55e-11e7-9611-bd9a29d660a1.png">

Right side

### Tasks
- [ ] Populating action name (create action service?)
- [ ] Populating risk name (create risk service?)
- [ ] Populating category icons (create category service?)
- [ ] Edit button (no function)
