### ISSUE TITLE
User should be able to choose a suggested action before opening the action wizard

### ISSUE THREAD

**Issue by fungjj92** [azavea/temperate#418]
### Description
User should be able to choose a suggested action before opening the action wizard

### Screenshots
![screen shot 2018-01-09 at 3 15 32 pm](https://user-images.githubusercontent.com/10568752/34741280-191ae8b4-f550-11e7-864b-8e80acabc150.png)

![screen shot 2018-01-09 at 3 15 24 pm](https://user-images.githubusercontent.com/10568752/34741286-1f56a84e-f550-11e7-90f3-bfad7b6dacaf.png)

![screen shot 2018-01-09 at 3 16 23 pm](https://user-images.githubusercontent.com/10568752/34741295-24c33036-f550-11e7-9f4a-c2f6f75dc897.png)

### Tasks
- [ ] Create the static initial wizard modal. View at route like: /actions/action/start
- [ ] Direct 'take action' button to the above route
- [ ] Create a bare bones suggested actions view, with no action cards. View at route like: /actions/actions/suggested
- [ ] Route appropriately to the action wizard
