### ISSUE TITLE
User should be able to create an action from an existing risk

### ISSUE THREAD

**Issue by fungjj92** [azavea/temperate#426]
### Description
This will likely be tricky. Passing dynamic data across routes is a little limited, and multi-step.
See: https://blog.thoughtram.io/angular/2016/10/10/resolving-route-data-in-angular-2.html

Passing the risk to prevent duplicate requests and modifying the route with, say, a risk id would be the ideal.

### Screenshots

![screen shot 2018-01-09 at 3 15 32 pm](https://user-images.githubusercontent.com/10568752/34791235-600cf47a-f612-11e7-985e-18b3cc90c384.png)

<img width="612" alt="screen shot 2018-01-10 at 2 28 37 pm" src="https://user-images.githubusercontent.com/10568752/34791296-92e8a7b8-f612-11e7-9769-e13bec6cc0f8.png">

### Tasks
- [ ] Hook this up through the 'take action' button o the action steps page
- [ ] Make sure the action wizard received the risk in step 1
- [ ] The typeahead and title in step 1 should be set to the selected risk
