### ISSUE TITLE
Add Missy's dataset to the Django database for the suggested actions work

### ISSUE THREAD

**Issue by fungjj92** [azavea/temperate#451]
### Description

Create a script that processes the [strategies with weather events](https://docs.google.com/spreadsheets/d/1ryNBsNDQ7Nc7mIpIZl0PLbT4kLzMd3yKW6LFz3xsYAI/edit#gid=1370719142) and [cities](https://docs.google.com/spreadsheets/d/1ryNBsNDQ7Nc7mIpIZl0PLbT4kLzMd3yKW6LFz3xsYAI/edit#gid=489883855) tabs into `Organization`s, `Action`s, `OrganizationalRisk`s, and `AdaptationPlan`s in the Django database.

The desired goal, as per a meeting, will be for the CSV information to end up as such:

Each "city"'s data will be processed under an adaptation plan under a new organization. A complete line in the CSV contains enough data for a risk and an associated action. More detail later on incomplete lines. Some models need to be created and tweaked. The organizations created don't represent real orgs, but rather are dummies needed to house the data.

### Demo

This data is essential information for the suggested actions workflow of the action steps feature, which flows as such:

![screen shot 2018-01-09 at 3 15 32 pm](https://user-images.githubusercontent.com/10568752/34958526-5779693c-fa00-11e7-8f1a-9b1487beafe0.png)
 

![screen shot 2018-01-09 at 3 15 24 pm](https://user-images.githubusercontent.com/10568752/34958516-484ffb60-fa00-11e7-9b73-2b478781fc0a.png)

![screen shot 2018-01-09 at 3 16 23 pm](https://user-images.githubusercontent.com/10568752/34958520-4ccc3a50-fa00-11e7-86f2-92a5ee0e3b5a.png)

### Tasks
- [x] ~Create the AdaptationPlan model and set a multifield association to Organization because orgs can have multiple plans~
       Add fields to organization: plan year, plan hyperlink, plan name
- [x] OrganizationalRisk should allow WeatherEvent or CommunitySystem to be blank, with `default=''`. This prepares for the known case of only one piece of that info. 
- [x] Validation and tests for above
- [x] An `Organization` should be created for each CSV "City". ~You'll need "PlanItLocation"s for each -- in most cases, you'll need to create new ones.~ Name field, plan name, plan year, plan hyperlink are sufficient.
- [x] Create a barebones `OrganizationalRisk` from the weather event and community systems column. There may be multiple semicolon delineated weather events or community systems for which a unique `OrganizationalRisk` should be created. If there is no weather or community system, then skip that line
- [x] Create an `Action` that takes the above risk, and has filled in its name, categories.
- [x] Sensibly log activity to the terminal as the job runs
