### ISSUE TITLE
User should see risk info header in action wizard

### ISSUE THREAD

**Issue by fungjj92** [azavea/temperate#478]
### Description
The action wizard currently has no header.
The user should always see a risk and it's corresponding adaptive need value in the header.

In the newest version of Temperate, a user won't be able to create an action totally from scratch. They will have to select "take action" on a risk, so don't worry about that case.

### Demo

<img width="492" alt="screen shot 2018-01-23 at 10 55 59 am" src="https://user-images.githubusercontent.com/10568752/35285683-083d88d0-002c-11e8-9817-ad6d83dc8bf4.png">

### Tasks
- [ ] User should see the header with risk name and tooltip for adaptive capacity
- [ ] User should see the risk dropdown in Step 1 preselected (possibly completed by #471)
- [ ] User should see the header update info when a new risk is selected from the dropdown
